name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Docker Build
        run: |-
          docker build . -f docker/prod.Dockerfile -t southamerica-east1-docker.pkg.dev/luanlmd-384622/images/luanlmd:latest
          docker push southamerica-east1-docker.pkg.dev/luanlmd-384622/images/luanlmd:latest